name: Workflow
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: null
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: List contents
        run: ls
      - name: compile classes
        working-directory: ./src
        run: >-
          javac -cp 
          "../testresources/junit-platform-console-standalone-1.6.0.jar" 
          "./poe5121_part_1_and_2/Login.java" "./poe5121_part_1_and_2/POE5121_Part_1_And_2.java" "./poe5121_part_1_and_2/Tasks.java" 
          "../test/poe5121_part_1_and_2/LoginTest.java" "../test/poe5121_part_1_and_2/TasksTest.java"
      - name: List contents of src directory after compile
        working-directory: ./src/poe5121_part_1_and_2
        run: ls
      - name: create testresources/poe5121_part_1_and_2 directory
        run: mkdir -p ./testresources/poe5121_part_1_and_2
      - name: copy compiled classes to testresources directory
        working-directory: ./src/poe5121_part_1_and_2
        run: cp -t  "../../test/poe5121_part_1_and_2 " Login.class POE5121_Part_1_And_2.class Tasks.class
      - name: copy compiled Test classes to testresources directory
        working-directory: ./test/poe5121_part_1_and_2
        run: cp -t  "../../testresources/packageName" LoginTest.class TasksTest.class
      - name: List contents test package
        working-directory: ./test/poe5121_part_1_and_2
        run: ls
